%This is the change file for the original Docker's Documentation file.
%This is part of Japanese translation version for Docker's Documantation.

@x
---
title: "Use containers for development"
keywords: get started, go, golang, local, development
description: Learn how to develop your application locally.
redirect_from:
- /get-started/golang/develop/
---
@y
---
title: "Use containers for development"
keywords: get started, go, golang, local, development
description: Learn how to develop your application locally.
redirect_from:
- /get-started/golang/develop/
---
@z

@x
{% include_relative nav.html selected="3" %}
@y
{% include_relative nav.html selected="3" %}
@z

@x
## Prerequisites
@y
## Prerequisites
@z

@x
Work through the steps of the [run your image as a container](run-containers.md) module to learn how to manage the lifecycle of your containers.
@y
Work through the steps of the [run your image as a container](run-containers.md) module to learn how to manage the lifecycle of your containers.
@z

@x
## Introduction
@y
## Introduction
@z

@x
In this module, we'll take a look at running a database engine in a container and connecting it to the extended version of the example application. We are going to see some options for keeping persistent data and for wiring up the containers to talk to one another. Finally, we'll learn how to use Docker Compose to manage such multi-container local development environments effectively.
@y
In this module, we'll take a look at running a database engine in a container and connecting it to the extended version of the example application. We are going to see some options for keeping persistent data and for wiring up the containers to talk to one another. Finally, we'll learn how to use Docker Compose to manage such multi-container local development environments effectively.
@z

@x
## Local database and containers
@y
## Local database and containers
@z

@x
The database engine we are going to use is called [CockroachDB](https://www.cockroachlabs.com/product/). It is a modern, Cloud-native, distributed SQL database.
@y
The database engine we are going to use is called [CockroachDB](https://www.cockroachlabs.com/product/). It is a modern, Cloud-native, distributed SQL database.
@z

@x
Instead of compiling CockroachDB from the source code or using the operating system's native package manager to install CockroachDB, we are going to use the [Docker image for CockroachDB](https://hub.docker.com/r/cockroachdb/cockroach) and run it in a container.
@y
Instead of compiling CockroachDB from the source code or using the operating system's native package manager to install CockroachDB, we are going to use the [Docker image for CockroachDB](https://hub.docker.com/r/cockroachdb/cockroach) and run it in a container.
@z

@x
CockroachDB is compatible with PostgreSQL to a significant extent, and shares many conventions with the latter, particularly the default names for the environment variables. So, if you are familiar with Postgres, don't be surprised that we are going to use some familiar environment variables names. The Go modules that work with Postgres, such as [pgx](https://pkg.go.dev/github.com/jackc/pgx), [pq](https://pkg.go.dev/github.com/lib/pq), [GORM](https://gorm.io/index.html), and [upper/db](https://upper.io/v4/) also work with CockroachDB.
@y
CockroachDB is compatible with PostgreSQL to a significant extent, and shares many conventions with the latter, particularly the default names for the environment variables. So, if you are familiar with Postgres, don't be surprised that we are going to use some familiar environment variables names. The Go modules that work with Postgres, such as [pgx](https://pkg.go.dev/github.com/jackc/pgx), [pq](https://pkg.go.dev/github.com/lib/pq), [GORM](https://gorm.io/index.html), and [upper/db](https://upper.io/v4/) also work with CockroachDB.
@z

@x
For more information on the relation between Go and CockroachDB, please refer to the [CockroachDB documentation](https://www.cockroachlabs.com/docs/v20.2/build-a-go-app-with-cockroachdb.html), although this is not necessary to continue with the present guide.
@y
For more information on the relation between Go and CockroachDB, please refer to the [CockroachDB documentation](https://www.cockroachlabs.com/docs/v20.2/build-a-go-app-with-cockroachdb.html), although this is not necessary to continue with the present guide.
@z

@x
### Storage
@y
### Storage
@z

@x
The point of a database is to have a persistent store of data. [Volumes](../../storage/volumes.md) are the preferred mechanism for persisting data generated by and used by Docker containers. Thus, before we start CockroachDB, let's create the volume for it.
@y
The point of a database is to have a persistent store of data. [Volumes](../../storage/volumes.md) are the preferred mechanism for persisting data generated by and used by Docker containers. Thus, before we start CockroachDB, let's create the volume for it.
@z

@x
To create a managed volume, run :
@y
To create a managed volume, run :
@z

@x
```console
$ docker volume create roach
roach
```
@y
```console
$ docker volume create roach
roach
```
@z

@x
We can view the list of all managed volumes in our Docker instance with the following command:
@y
We can view the list of all managed volumes in our Docker instance with the following command:
@z

@x
```console
$ docker volume list
DRIVER    VOLUME NAME
local     roach
```
@y
```console
$ docker volume list
DRIVER    VOLUME NAME
local     roach
```
@z

@x
### Networking
@y
### Networking
@z

@x
The example application and the database engine are going to talk to one another over the network. There are different kinds of network configuration possible, and we are going to use what is called a user-defined _bridge network_. It is going to provide us with a DNS lookup service so that we can refer to our database enginer container by its host name.
@y
The example application and the database engine are going to talk to one another over the network. There are different kinds of network configuration possible, and we are going to use what is called a user-defined _bridge network_. It is going to provide us with a DNS lookup service so that we can refer to our database enginer container by its host name.
@z

@x
The following command creates a new bridge network named `mynet`:
@y
The following command creates a new bridge network named `mynet`:
@z

@x
```console
$ docker network create -d bridge mynet
51344edd6430b5acd121822cacc99f8bc39be63dd125a3b3cd517b6485ab7709
```
@y
```console
$ docker network create -d bridge mynet
51344edd6430b5acd121822cacc99f8bc39be63dd125a3b3cd517b6485ab7709
```
@z

@x
As it was the case with the managed volumes, there is a command to list all networks set up in your Docker instance:
@y
As it was the case with the managed volumes, there is a command to list all networks set up in your Docker instance:
@z

@x
```console
$ docker network list
NETWORK ID     NAME          DRIVER    SCOPE
0ac2b1819fa4   bridge        bridge    local
51344edd6430   mynet         bridge    local
daed20bbecce   host          host      local
6aee44f40a39   none          null      local
```
@y
```console
$ docker network list
NETWORK ID     NAME          DRIVER    SCOPE
0ac2b1819fa4   bridge        bridge    local
51344edd6430   mynet         bridge    local
daed20bbecce   host          host      local
6aee44f40a39   none          null      local
```
@z

@x
Our bridge network `mynet` has been created successfully. The other three networks, named `bridge`, `host`, and `none` are the _default_ networks and they had been created by the Docker itself. While it is not relevant to our current discussion, you can learn more about Docker networking in the [networking overview](../../network/index.md) section.
@y
Our bridge network `mynet` has been created successfully. The other three networks, named `bridge`, `host`, and `none` are the _default_ networks and they had been created by the Docker itself. While it is not relevant to our current discussion, you can learn more about Docker networking in the [networking overview](../../network/index.md) section.
@z

@x
### Choose good names for volumes and networks
@y
### Choose good names for volumes and networks
@z

@x
As the saying goes, there are only two hard things in Computer Science: cache invalidation and naming things. And off-by-one errors.
@y
As the saying goes, there are only two hard things in Computer Science: cache invalidation and naming things. And off-by-one errors.
@z

@x
When choosing a name for a network or a managed volume, it's best to choose a name which is indicative of the intended purpose. In this module, though, we aimed for brevity, so we settled for short, generic names.
@y
When choosing a name for a network or a managed volume, it's best to choose a name which is indicative of the intended purpose. In this module, though, we aimed for brevity, so we settled for short, generic names.
@z

@x
### Start the database engine
@y
### Start the database engine
@z

@x
Now that the housekeeping chores are done, we can run CockroachDB in a container and attach it to the volume and network we had just created. When you run the folllowing command, Docker will pull the image from Docker Hub and run it for you locally:
@y
Now that the housekeeping chores are done, we can run CockroachDB in a container and attach it to the volume and network we had just created. When you run the folllowing command, Docker will pull the image from Docker Hub and run it for you locally:
@z

@x
```console
$ docker run -d \
  --name roach \
  --hostname db \
  --network mynet \
  -p 26257:26257 \
  -p 8080:8080 \
  -v roach:/cockroach/cockroach-data \
  cockroachdb/cockroach:latest-v20.1 start-single-node \
  --insecure
@y
```console
$ docker run -d \
  --name roach \
  --hostname db \
  --network mynet \
  -p 26257:26257 \
  -p 8080:8080 \
  -v roach:/cockroach/cockroach-data \
  cockroachdb/cockroach:latest-v20.1 start-single-node \
  --insecure
@z

@x
# ... output omitted ...
```
@y
# ... output omitted ...
```
@z

@x
Notice a clever use of the tag `latest-v20.1` to make sure that we are pulling the latest patch version of 20.1.  The diversity of available tags depend on the image maintainer. Here, our intent was to have the latest patched version of CockroachDB while not straying too far away from the known working version as the time goes by. To see the tags available for CockroachDB image, we went to [CockroachDB page on Docker Hub](https://hub.docker.com/r/cockroachdb/cockroach/tags).
@y
Notice a clever use of the tag `latest-v20.1` to make sure that we are pulling the latest patch version of 20.1.  The diversity of available tags depend on the image maintainer. Here, our intent was to have the latest patched version of CockroachDB while not straying too far away from the known working version as the time goes by. To see the tags available for CockroachDB image, we went to [CockroachDB page on Docker Hub](https://hub.docker.com/r/cockroachdb/cockroach/tags).
@z

@x
### Configure the database engine
@y
### Configure the database engine
@z

@x
Now that the database engine is live, there is some configuration to do before our application can begin using it. Fortunately, it's not a lot. We must:
@y
Now that the database engine is live, there is some configuration to do before our application can begin using it. Fortunately, it's not a lot. We must:
@z

@x
1. Create a blank database.
2. Register a new user account with the database engine.
3. Grant that new user access rights to the database.
@y
1. Create a blank database.
2. Register a new user account with the database engine.
3. Grant that new user access rights to the database.
@z

@x
We can do that with the help of CockroachDB built-in SQL shell. To start the SQL shell in the _same_ container where the database engine is running, type:
@y
We can do that with the help of CockroachDB built-in SQL shell. To start the SQL shell in the _same_ container where the database engine is running, type:
@z

@x
```console
$ docker exec -it roach ./cockroach sql --insecure
```
@y
```console
$ docker exec -it roach ./cockroach sql --insecure
```
@z

@x
1. In the SQL shell, create the database that our example application is going to use:
@y
1. In the SQL shell, create the database that our example application is going to use:
@z

@x
   ```sql
   CREATE DATABASE mydb;
   ```
@y
   ```sql
   CREATE DATABASE mydb;
   ```
@z

@x
2. Register a new SQL user account with the database engine. We pick the username `totoro`.
@y
2. Register a new SQL user account with the database engine. We pick the username `totoro`.
@z

@x
   ```sql
   CREATE USER totoro;
   ```
@y
   ```sql
   CREATE USER totoro;
   ```
@z

@x
3. Give the new user the necessary permissions:
@y
3. Give the new user the necessary permissions:
@z

@x
   ```sql
   GRANT ALL ON DATABASE mydb TO totoro;
   ```
@y
   ```sql
   GRANT ALL ON DATABASE mydb TO totoro;
   ```
@z

@x
4. Type `quit` to exit the shell. 
@y
4. Type `quit` to exit the shell. 
@z

@x
An example of interaction with the SQL shell is presented below.
@y
An example of interaction with the SQL shell is presented below.
@z

@x
{% raw %}
```console
$ sudo docker exec -it roach ./cockroach sql --insecure
#
# Welcome to the CockroachDB SQL shell.
# All statements must be terminated by a semicolon.
# To exit, type: \q.
#
# Server version: CockroachDB CCL v20.1.15 (x86_64-unknown-linux-gnu, built 2021/04/26 16:11:58, go1.13.9) (same version as client)
# Cluster ID: 7f43a490-ccd6-4c2a-9534-21f393ca80ce
#
# Enter \? for a brief introduction.
#
root@:26257/defaultdb> CREATE DATABASE mydb;
CREATE DATABASE
@y
{% raw %}
```console
$ sudo docker exec -it roach ./cockroach sql --insecure
#
# Welcome to the CockroachDB SQL shell.
# All statements must be terminated by a semicolon.
# To exit, type: \q.
#
# Server version: CockroachDB CCL v20.1.15 (x86_64-unknown-linux-gnu, built 2021/04/26 16:11:58, go1.13.9) (same version as client)
# Cluster ID: 7f43a490-ccd6-4c2a-9534-21f393ca80ce
#
# Enter \? for a brief introduction.
#
root@:26257/defaultdb> CREATE DATABASE mydb;
CREATE DATABASE
@z

@x
Time: 22.985478ms
@y
Time: 22.985478ms
@z

@x
root@:26257/defaultdb> CREATE USER totoro;
CREATE ROLE
@y
root@:26257/defaultdb> CREATE USER totoro;
CREATE ROLE
@z

@x
Time: 13.921659ms
@y
Time: 13.921659ms
@z

@x
root@:26257/defaultdb> GRANT ALL ON DATABASE mydb TO totoro;
GRANT
@y
root@:26257/defaultdb> GRANT ALL ON DATABASE mydb TO totoro;
GRANT
@z

@x
Time: 14.217559ms
@y
Time: 14.217559ms
@z

@x
root@:26257/defaultdb> quit
oliver@hki:~$
```
{% endraw %}
@y
root@:26257/defaultdb> quit
oliver@hki:~$
```
{% endraw %}
@z

@x
### Meet the example application
@y
### Meet the example application
@z

@x
Now that we have started and configured the database engine, we can swith our attention to the application. 
@y
Now that we have started and configured the database engine, we can swith our attention to the application. 
@z

@x
The example application for this module is an extended version of `docker-gs-ping` application we've used in the previous modules. You have two options:
@y
The example application for this module is an extended version of `docker-gs-ping` application we've used in the previous modules. You have two options:
@z

@x
* You can update your local copy of `docker-gs-ping` to match the new extended version presented in this chapter; or
* You can clone the [olliefr/docker-gs-ping-roach](https://github.com/olliefr/docker-gs-ping-roach) repo. This latter approach is recommended.
@y
* You can update your local copy of `docker-gs-ping` to match the new extended version presented in this chapter; or
* You can clone the [olliefr/docker-gs-ping-roach](https://github.com/olliefr/docker-gs-ping-roach) repo. This latter approach is recommended.
@z

@x
To checkout the example application, run:
@y
To checkout the example application, run:
@z

@x
```console
$ git clone https://github.com/olliefr/docker-gs-ping-roach.git
# ... output omitted ...
```
@y
```console
$ git clone https://github.com/olliefr/docker-gs-ping-roach.git
# ... output omitted ...
```
@z

@x
The application's `main.go` now includes database initialisation code, as well as the code to implement a new business requirement:
@y
The application's `main.go` now includes database initialisation code, as well as the code to implement a new business requirement:
@z

@x
* An HTTP `POST` request to `/send` containing a `{ "value" : string }` JSON must save the value to the database.
@y
* An HTTP `POST` request to `/send` containing a `{ "value" : string }` JSON must save the value to the database.
@z

@x
We also have an update for another business requirement. The requirement _was_:
@y
We also have an update for another business requirement. The requirement _was_:
@z

@x
* The application responds with a text message containing a heart symbol ("`<3`") on requests to `/`.
@y
* The application responds with a text message containing a heart symbol ("`<3`") on requests to `/`.
@z

@x
And _now_ it's going to be:
@y
And _now_ it's going to be:
@z

@x
* The application responds with the string containing the count of messages stored in the database, enclosed in the parentheses. 
@y
* The application responds with the string containing the count of messages stored in the database, enclosed in the parentheses. 
@z

@x
   Example output: `Hello, Docker! (7)`
@y
   Example output: `Hello, Docker! (7)`
@z

@x
The full source code listing of `main.go` follows.
@y
The full source code listing of `main.go` follows.
@z

@x
{% raw %}
```go
package main
@y
{% raw %}
```go
package main
@z

@x
import (
	"context"
	"database/sql"
	"fmt"
	"log"
	"net/http"
	"os"
@y
import (
	"context"
	"database/sql"
	"fmt"
	"log"
	"net/http"
	"os"
@z

@x
	"github.com/cenkalti/backoff/v4"
	"github.com/cockroachdb/cockroach-go/v2/crdb"
	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
)
@y
	"github.com/cenkalti/backoff/v4"
	"github.com/cockroachdb/cockroach-go/v2/crdb"
	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
)
@z

@x
func main() {
@y
func main() {
@z

@x
	e := echo.New()
@y
	e := echo.New()
@z

@x
	e.Use(middleware.Logger())
	e.Use(middleware.Recover())
@y
	e.Use(middleware.Logger())
	e.Use(middleware.Recover())
@z

@x
	db, err := initStore()
	if err != nil {
		log.Fatalf("failed to initialise the store: %s", err)
	}
	defer db.Close()
@y
	db, err := initStore()
	if err != nil {
		log.Fatalf("failed to initialise the store: %s", err)
	}
	defer db.Close()
@z

@x
	e.GET("/", func(c echo.Context) error {
		return rootHandler(db, c)
	})
@y
	e.GET("/", func(c echo.Context) error {
		return rootHandler(db, c)
	})
@z

@x
	e.GET("/ping", func(c echo.Context) error {
		return c.JSON(http.StatusOK, struct{ Status string }{Status: "OK"})
	})
@y
	e.GET("/ping", func(c echo.Context) error {
		return c.JSON(http.StatusOK, struct{ Status string }{Status: "OK"})
	})
@z

@x
	e.POST("/send", func(c echo.Context) error {
		return sendHandler(db, c)
	})
@y
	e.POST("/send", func(c echo.Context) error {
		return sendHandler(db, c)
	})
@z

@x
	httpPort := os.Getenv("HTTP_PORT")
	if httpPort == "" {
		httpPort = "8080"
	}
@y
	httpPort := os.Getenv("HTTP_PORT")
	if httpPort == "" {
		httpPort = "8080"
	}
@z

@x
	e.Logger.Fatal(e.Start(":" + httpPort))
}
@y
	e.Logger.Fatal(e.Start(":" + httpPort))
}
@z

@x
type Message struct {
	Value string `json:"value"`
}
@y
type Message struct {
	Value string `json:"value"`
}
@z

@x
func initStore() (*sql.DB, error) {
@y
func initStore() (*sql.DB, error) {
@z

@x
	pgConnString := fmt.Sprintf("host=%s port=%s dbname=%s user=%s password=%s sslmode=disable",
		os.Getenv("PGHOST"),
		os.Getenv("PGPORT"),
		os.Getenv("PGDATABASE"),
		os.Getenv("PGUSER"),
		os.Getenv("PGPASSWORD"),
	)
@y
	pgConnString := fmt.Sprintf("host=%s port=%s dbname=%s user=%s password=%s sslmode=disable",
		os.Getenv("PGHOST"),
		os.Getenv("PGPORT"),
		os.Getenv("PGDATABASE"),
		os.Getenv("PGUSER"),
		os.Getenv("PGPASSWORD"),
	)
@z

@x
	var (
		db  *sql.DB
		err error
	)
	openDB := func() error {
		db, err = sql.Open("postgres", pgConnString)
		return err
	}
@y
	var (
		db  *sql.DB
		err error
	)
	openDB := func() error {
		db, err = sql.Open("postgres", pgConnString)
		return err
	}
@z

@x
	err = backoff.Retry(openDB, backoff.NewExponentialBackOff())
	if err != nil {
		return nil, err
	}
@y
	err = backoff.Retry(openDB, backoff.NewExponentialBackOff())
	if err != nil {
		return nil, err
	}
@z

@x
	if _, err := db.Exec(
		"CREATE TABLE IF NOT EXISTS message (value STRING PRIMARY KEY)"); err != nil {
		return nil, err
	}
@y
	if _, err := db.Exec(
		"CREATE TABLE IF NOT EXISTS message (value STRING PRIMARY KEY)"); err != nil {
		return nil, err
	}
@z

@x
	return db, nil
}
@y
	return db, nil
}
@z

@x
func rootHandler(db *sql.DB, c echo.Context) error {
	r, err := countRecords(db)
	if err != nil {
		return c.HTML(http.StatusInternalServerError, err.Error())
	}
	return c.HTML(http.StatusOK, fmt.Sprintf("Hello, Docker! (%d)\n", r))
}
@y
func rootHandler(db *sql.DB, c echo.Context) error {
	r, err := countRecords(db)
	if err != nil {
		return c.HTML(http.StatusInternalServerError, err.Error())
	}
	return c.HTML(http.StatusOK, fmt.Sprintf("Hello, Docker! (%d)\n", r))
}
@z

@x
func sendHandler(db *sql.DB, c echo.Context) error {
@y
func sendHandler(db *sql.DB, c echo.Context) error {
@z

@x
	m := &Message{}
@y
	m := &Message{}
@z

@x
	if err := c.Bind(m); err != nil {
		return c.JSON(http.StatusInternalServerError, err)
	}
@y
	if err := c.Bind(m); err != nil {
		return c.JSON(http.StatusInternalServerError, err)
	}
@z

@x
	err := crdb.ExecuteTx(context.Background(), db, nil,
		func(tx *sql.Tx) error {
			_, err := tx.Exec(
				"INSERT INTO message (value) VALUES ($1) ON CONFLICT (value) DO UPDATE SET value = excluded.value",
				m.Value,
			)
			if err != nil {
				return c.JSON(http.StatusInternalServerError, err)
			}
			return nil
		})
@y
	err := crdb.ExecuteTx(context.Background(), db, nil,
		func(tx *sql.Tx) error {
			_, err := tx.Exec(
				"INSERT INTO message (value) VALUES ($1) ON CONFLICT (value) DO UPDATE SET value = excluded.value",
				m.Value,
			)
			if err != nil {
				return c.JSON(http.StatusInternalServerError, err)
			}
			return nil
		})
@z

@x
	if err != nil {
		return c.JSON(http.StatusInternalServerError, err)
	}
@y
	if err != nil {
		return c.JSON(http.StatusInternalServerError, err)
	}
@z

@x
	return c.JSON(http.StatusOK, m)
}
@y
	return c.JSON(http.StatusOK, m)
}
@z

@x
func countRecords(db *sql.DB) (int, error) {
@y
func countRecords(db *sql.DB) (int, error) {
@z

@x
	rows, err := db.Query("SELECT COUNT(*) FROM message")
	if err != nil {
		return 0, err
	}
	defer rows.Close()
@y
	rows, err := db.Query("SELECT COUNT(*) FROM message")
	if err != nil {
		return 0, err
	}
	defer rows.Close()
@z

@x
	count := 0
	for rows.Next() {
		if err := rows.Scan(&count); err != nil {
			return 0, err
		}
		rows.Close()
	}
@y
	count := 0
	for rows.Next() {
		if err := rows.Scan(&count); err != nil {
			return 0, err
		}
		rows.Close()
	}
@z

@x
	return count, nil
}
```
{% endraw %}
@y
	return count, nil
}
```
{% endraw %}
@z

@x
The repository also includes the `Dockerfile`, which is almost exactly the same as the multi-stage `Dockerfile` introduced in the previous modules. It uses official Docker Go image to build the application and then builds the final image by placing the compiled binary into the much slimmer, "distroless" image.
@y
The repository also includes the `Dockerfile`, which is almost exactly the same as the multi-stage `Dockerfile` introduced in the previous modules. It uses official Docker Go image to build the application and then builds the final image by placing the compiled binary into the much slimmer, "distroless" image.
@z

@x
Regardless of whether we had updated the old example application, or checked out the new one, this new Docker image has to be built to reflect the changes to the application source code.
@y
Regardless of whether we had updated the old example application, or checked out the new one, this new Docker image has to be built to reflect the changes to the application source code.
@z

@x
### Build the application
@y
### Build the application
@z

@x
We can build the image with the familiar `build` command:
@y
We can build the image with the familiar `build` command:
@z

@x
```console
$ docker build --tag docker-gs-ping-roach .
```
@y
```console
$ docker build --tag docker-gs-ping-roach .
```
@z

@x
### Run the application
@y
### Run the application
@z

@x
Now, let’s run our container. This time we’ll need to set some environment variables so that our application would know how to access the database. For now, we’ll do this right in the `docker run` command. Later we will see a more convenient method with Docker Compose.
@y
Now, let’s run our container. This time we’ll need to set some environment variables so that our application would know how to access the database. For now, we’ll do this right in the `docker run` command. Later we will see a more convenient method with Docker Compose.
@z

@x
> **Note**
>
> Since we are running our CockroachDB cluster in "insecure" mode, the value for the password can be anything. 
> 
> **Don't run in insecure mode in production, though!**
@y
> **Note**
>
> Since we are running our CockroachDB cluster in "insecure" mode, the value for the password can be anything. 
> 
> **Don't run in insecure mode in production, though!**
@z

@x
```console
$ docker run -it --rm -d \
  --network mynet \
  --name rest-server \
  -p 80:8080 \
  -e PGUSER=totoro \
  -e PGPASSWORD=myfriend \
  -e PGHOST=db \
  -e PGPORT=26257 \
  -e PGDATABASE=mydb \
  docker-gs-ping-roach
```
@y
```console
$ docker run -it --rm -d \
  --network mynet \
  --name rest-server \
  -p 80:8080 \
  -e PGUSER=totoro \
  -e PGPASSWORD=myfriend \
  -e PGHOST=db \
  -e PGPORT=26257 \
  -e PGDATABASE=mydb \
  docker-gs-ping-roach
```
@z

@x
There are a few points to note about this command.
@y
There are a few points to note about this command.
@z

@x
* We map container port `8080` to host port `80` this time. Thus, for `GET` requests we can get away with _literally_ `curl localhost`:
@y
* We map container port `8080` to host port `80` this time. Thus, for `GET` requests we can get away with _literally_ `curl localhost`:
@z

@x
  ```console
  $ curl localhost
  Hello, Docker! (0)
  ```
@y
  ```console
  $ curl localhost
  Hello, Docker! (0)
  ```
@z

@x
  Or, if you prefer, a proper URL would work just as well:
@y
  Or, if you prefer, a proper URL would work just as well:
@z

@x
  ```console
  $ curl http://localhost/
  Hello, Docker! (0)
  ```
@y
  ```console
  $ curl http://localhost/
  Hello, Docker! (0)
  ```
@z

@x
* The total number of stored messages is `0` for now. This is fine, because we had not posted anything to our application yet.
* We refer to the database container by its hostname, which is `db`. This is what we had the `--name db` for when we started the database container.
@y
* The total number of stored messages is `0` for now. This is fine, because we had not posted anything to our application yet.
* We refer to the database container by its hostname, which is `db`. This is what we had the `--name db` for when we started the database container.
@z

@x
* The actual password does not matter, but it must be set to something to avoid confusing the example application.
* The container we've just run is named `rest-server`. These names are useful for managing the container lifecycle:
@y
* The actual password does not matter, but it must be set to something to avoid confusing the example application.
* The container we've just run is named `rest-server`. These names are useful for managing the container lifecycle:
@z

@x
  ```console
  # Don't do this just yet, it's only an example:
  $ docker container rm --force rest-server
  ```
@y
  ```console
  # Don't do this just yet, it's only an example:
  $ docker container rm --force rest-server
  ```
@z

@x
### Test the application
@y
### Test the application
@z

@x
In the previous section, we have already tested querying our application with `GET` and it returned zero for the stored message counter. Now, let's post some messages to it:
@y
In the previous section, we have already tested querying our application with `GET` and it returned zero for the stored message counter. Now, let's post some messages to it:
@z

@x
```console
$ curl --request POST \
  --url http://localhost/send \
  --header 'content-type: application/json' \
  --data '{"value": "Hello, Docker!"}'
```
@y
```console
$ curl --request POST \
  --url http://localhost/send \
  --header 'content-type: application/json' \
  --data '{"value": "Hello, Docker!"}'
```
@z

@x
The application responds with the contents of the message, which means it had been saved in the database:
@y
The application responds with the contents of the message, which means it had been saved in the database:
@z

@x
```json
{"value":"Hello, Docker!"}
```
@y
```json
{"value":"Hello, Docker!"}
```
@z

@x
Let's send another message:
@y
Let's send another message:
@z

@x
```console
$ curl --request POST \
  --url http://localhost/send \
  --header 'content-type: application/json' \
  --data '{"value": "Hello, Oliver!"}'
```
@y
```console
$ curl --request POST \
  --url http://localhost/send \
  --header 'content-type: application/json' \
  --data '{"value": "Hello, Oliver!"}'
```
@z

@x
And again, we get the value of the message back:
@y
And again, we get the value of the message back:
@z

@x
```json
{"value":"Hello, Oliver!"}
```
@y
```json
{"value":"Hello, Oliver!"}
```
@z

@x
Let's see what the message counter says:
@y
Let's see what the message counter says:
@z

@x
```console
$ curl localhost
Hello, Docker! (2)
```
@y
```console
$ curl localhost
Hello, Docker! (2)
```
@z

@x
Hey, that's exactly right! We sent two messages and the database kept them. Or has it? Let's stop and remove all our containers, but not the volumes, and try again.
@y
Hey, that's exactly right! We sent two messages and the database kept them. Or has it? Let's stop and remove all our containers, but not the volumes, and try again.
@z

@x
First, let's stop the containers:
@y
First, let's stop the containers:
@z

@x
```console
$ docker container stop rest-server roach
rest-server
roach
```
@y
```console
$ docker container stop rest-server roach
rest-server
roach
```
@z

@x
Then, let's remove them:
@y
Then, let's remove them:
@z

@x
```console
$ docker container rm rest-server roach
rest-server
roach
```
@y
```console
$ docker container rm rest-server roach
rest-server
roach
```
@z

@x
Verify that they are gone:
@y
Verify that they are gone:
@z

@x
```console
$ docker container list --all
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
```
@y
```console
$ docker container list --all
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
```
@z

@x
And start them again, database first:
@y
And start them again, database first:
@z

@x
```console
$ docker run -d \
  --name roach \
  --hostname db \
  --network mynet \
  -p 26257:26257 \
  -p 8080:8080 \
  -v roach:/cockroach/cockroach-data \
  cockroachdb/cockroach:latest-v20.1 start-single-node \
  --insecure
```
@y
```console
$ docker run -d \
  --name roach \
  --hostname db \
  --network mynet \
  -p 26257:26257 \
  -p 8080:8080 \
  -v roach:/cockroach/cockroach-data \
  cockroachdb/cockroach:latest-v20.1 start-single-node \
  --insecure
```
@z

@x
And the service next:
@y
And the service next:
@z

@x
```console
$ docker run -it --rm -d \
  --network mynet \
  --name rest-server \
  -p 80:8080 \
  -e PGUSER=totoro \
  -e PGPASSWORD=myfriend \
  -e PGHOST=db \
  -e PGPORT=26257 \
  -e PGDATABASE=mydb \
  docker-gs-ping-roach
```
@y
```console
$ docker run -it --rm -d \
  --network mynet \
  --name rest-server \
  -p 80:8080 \
  -e PGUSER=totoro \
  -e PGPASSWORD=myfriend \
  -e PGHOST=db \
  -e PGPORT=26257 \
  -e PGDATABASE=mydb \
  docker-gs-ping-roach
```
@z

@x
Lastly, let's query our service:
@y
Lastly, let's query our service:
@z

@x
```console
$ curl localhost
Hello, Docker! (2)
```
@y
```console
$ curl localhost
Hello, Docker! (2)
```
@z

@x
Great! The count of records from the database is correct although we had not only _stopped_ the containers, but also removed them before starting new instances. The difference is in the managed volume for CockroachDB, which we had reused. The new CockroachDB container has read the database files from the disk, just as it normally would if it were running outside the container.
@y
Great! The count of records from the database is correct although we had not only _stopped_ the containers, but also removed them before starting new instances. The difference is in the managed volume for CockroachDB, which we had reused. The new CockroachDB container has read the database files from the disk, just as it normally would if it were running outside the container.
@z

@x
Such is the power of managed volumes. Use it wisely.
@y
Such is the power of managed volumes. Use it wisely.
@z

@x
### Wind down everything
@y
### Wind down everything
@z

@x
Remember, that we are running CockroachDB in "insecure" mode. Now that we had built and tested our application, it's time to wind everything down before moving on. You can list the containers that you are running with the `list` command:
@y
Remember, that we are running CockroachDB in "insecure" mode. Now that we had built and tested our application, it's time to wind everything down before moving on. You can list the containers that you are running with the `list` command:
@z

@x
```console
$ docker container list
```
@y
```console
$ docker container list
```
@z

@x
Now that you know the container IDs, you can use `docker container stop` and `docker container rm`, as demonstrated in the previous modules.
@y
Now that you know the container IDs, you can use `docker container stop` and `docker container rm`, as demonstrated in the previous modules.
@z

@x
Please make sure that you stop the CockroachDB and `docker-gs-ping-roach` containers before moving on.
@y
Please make sure that you stop the CockroachDB and `docker-gs-ping-roach` containers before moving on.
@z

@x
## Better productivity with Docker Compose
@y
## Better productivity with Docker Compose
@z

@x
At this point you might be wondering if there is a way to avoid having to deal with long lists of argument to the `docker` command. The toy example we used in this series requires five environment variables to define the connection to the database. A real application might need many, _many_ more. Then there is also a question of dependencies &ndash; ideally, we would like to make sure that the database is started _before_ our application is run. And spinning up the database instance may require another Docker command with many options. But there is a better way to orchestrate these deployments for local development purposes.
@y
At this point you might be wondering if there is a way to avoid having to deal with long lists of argument to the `docker` command. The toy example we used in this series requires five environment variables to define the connection to the database. A real application might need many, _many_ more. Then there is also a question of dependencies &ndash; ideally, we would like to make sure that the database is started _before_ our application is run. And spinning up the database instance may require another Docker command with many options. But there is a better way to orchestrate these deployments for local development purposes.
@z

@x
In this section, we’ll create a Docker Compose file to start our `docker-gs-ping-roach` application and CockroachDB database engine with a single command.
@y
In this section, we’ll create a Docker Compose file to start our `docker-gs-ping-roach` application and CockroachDB database engine with a single command.
@z

@x
### Configure Docker Compose
@y
### Configure Docker Compose
@z

@x
In our application's directory, create a new text file named `docker-compose.yml` with the following content.
@y
In our application's directory, create a new text file named `docker-compose.yml` with the following content.
@z

@x
{% raw %}
```yaml
version: '3.8'
@y
{% raw %}
```yaml
version: '3.8'
@z

@x
services:
  docker-gs-ping-roach:
    depends_on: 
      - roach
    build:
      context: .
    container_name: rest-server
    hostname: rest-server
    networks:
      - mynet
    ports:
      - 80:8080
    environment:
      - PGUSER=${PGUSER:-totoro}
      - PGPASSWORD=${PGPASSWORD:?database password not set}
      - PGHOST=${PGHOST:-db}
      - PGPORT=${PGPORT:-26257}
      - PGDATABASE=${PGDATABASE-mydb}
    deploy:
      restart_policy:
        condition: on-failure
  roach:
    image: cockroachdb/cockroach:latest-v20.1
    container_name: roach
    hostname: db
    networks:
      - mynet
    ports:
      - 26257:26257
      - 8080:8080
    volumes:
      - roach:/cockroach/cockroach-data
    command: start-single-node --insecure
@y
services:
  docker-gs-ping-roach:
    depends_on: 
      - roach
    build:
      context: .
    container_name: rest-server
    hostname: rest-server
    networks:
      - mynet
    ports:
      - 80:8080
    environment:
      - PGUSER=${PGUSER:-totoro}
      - PGPASSWORD=${PGPASSWORD:?database password not set}
      - PGHOST=${PGHOST:-db}
      - PGPORT=${PGPORT:-26257}
      - PGDATABASE=${PGDATABASE-mydb}
    deploy:
      restart_policy:
        condition: on-failure
  roach:
    image: cockroachdb/cockroach:latest-v20.1
    container_name: roach
    hostname: db
    networks:
      - mynet
    ports:
      - 26257:26257
      - 8080:8080
    volumes:
      - roach:/cockroach/cockroach-data
    command: start-single-node --insecure
@z

@x
volumes:
  roach:
@y
volumes:
  roach:
@z

@x
networks:
  mynet:
    driver: bridge
```
{% endraw %}
@y
networks:
  mynet:
    driver: bridge
```
{% endraw %}
@z

@x
This Docker Compose configuration is super convenient as we do not have to type all the parameters to pass to the `docker run` command. We can declaratively do that in the Docker Compose file. The [Docker Compose documentation pages](../../compose/index.md) are quite extensive and include a full reference for the Docker Compose file format.
@y
This Docker Compose configuration is super convenient as we do not have to type all the parameters to pass to the `docker run` command. We can declaratively do that in the Docker Compose file. The [Docker Compose documentation pages](../../compose/index.md) are quite extensive and include a full reference for the Docker Compose file format.
@z

@x
### The `.env` file
@y
### The `.env` file
@z

@x
Docker Compose will automatically read environment variables from a `.env` file if it is available. Since our Compose file requires `PGPASSWORD` to be set, we add the following content to the `.env` file:
@y
Docker Compose will automatically read environment variables from a `.env` file if it is available. Since our Compose file requires `PGPASSWORD` to be set, we add the following content to the `.env` file:
@z

@x
```bash
PGPASSWORD=whatever
```
@y
```bash
PGPASSWORD=whatever
```
@z

@x
The exact value does not really matter for our example, because we run CockroachDB in `insecure` mode, but we have to set the variable to _some_ value to avoid getting an error.
@y
The exact value does not really matter for our example, because we run CockroachDB in `insecure` mode, but we have to set the variable to _some_ value to avoid getting an error.
@z

@x
### Merging Compose files
@y
### Merging Compose files
@z

@x
The file name `docker-compose.yml` is the default file name which `docker-compose` command recognises if no `-f` flag is provided. This means you can have multiple Docker Compose files if your environment has such requirements. Furthermore, Docker Compose files are... composable (pun intended), so multiple files can be specified on the command line to merge parts of configuration together. The following list is just a few examples of scenarios where such feature would be very useful:
@y
The file name `docker-compose.yml` is the default file name which `docker-compose` command recognises if no `-f` flag is provided. This means you can have multiple Docker Compose files if your environment has such requirements. Furthermore, Docker Compose files are... composable (pun intended), so multiple files can be specified on the command line to merge parts of configuration together. The following list is just a few examples of scenarios where such feature would be very useful:
@z

@x
* Using a bind mount for the source code for local development but not when running the CI tests;
* Switching between using a pre-built image for the frontend for some API application vs creating a bind mount for source code;
* Adding additional services for integration testing;
* And many more...
@y
* Using a bind mount for the source code for local development but not when running the CI tests;
* Switching between using a pre-built image for the frontend for some API application vs creating a bind mount for source code;
* Adding additional services for integration testing;
* And many more...
@z

@x
We are not going to cover any of these advanced use cases here.
@y
We are not going to cover any of these advanced use cases here.
@z

@x
### Variable substitution in Docker Compose
@y
### Variable substitution in Docker Compose
@z

@x
One of the really cool features of Docker Compose is [variable substitution](../../compose/compose-file/compose-file-v3.md#variable-substitution). You can see some example in our Compose file, `environment` section. By means of example:
@y
One of the really cool features of Docker Compose is [variable substitution](../../compose/compose-file/compose-file-v3.md#variable-substitution). You can see some example in our Compose file, `environment` section. By means of example:
@z

@x
* `PGUSER=${PGUSER:-totoro}` means that inside the container, the environment variable `PGUSER` shall be set to the same value as it has on the host machine where Docker Compose is run. If there is no environment variable with this name on the host machine, the variable inside the container gets the default value of `totoro`.
* `PGPASSWORD=${PGPASSWORD:?database password not set}` means that if the environment variable `PGPASSWORD` is not set on the host, Docker Compose will display an error. This is OK, because we don't want to hard-code default values for the password. We set the password value in the `.env` file, which is local to our machine. It is always a good idea to add `.env` to `.gitignore` to prevent the secrets being checked into the version control.
@y
* `PGUSER=${PGUSER:-totoro}` means that inside the container, the environment variable `PGUSER` shall be set to the same value as it has on the host machine where Docker Compose is run. If there is no environment variable with this name on the host machine, the variable inside the container gets the default value of `totoro`.
* `PGPASSWORD=${PGPASSWORD:?database password not set}` means that if the environment variable `PGPASSWORD` is not set on the host, Docker Compose will display an error. This is OK, because we don't want to hard-code default values for the password. We set the password value in the `.env` file, which is local to our machine. It is always a good idea to add `.env` to `.gitignore` to prevent the secrets being checked into the version control.
@z

@x
Other ways of dealing with undefined or empty values exist, as documented in the [variable substitution](../../compose/compose-file/compose-file-v3.md#variable-substitution) section of the Docker documentation.
@y
Other ways of dealing with undefined or empty values exist, as documented in the [variable substitution](../../compose/compose-file/compose-file-v3.md#variable-substitution) section of the Docker documentation.
@z

@x
### Validating Docker Compose configuration
@y
### Validating Docker Compose configuration
@z

@x
Before you apply changes made to a Compose configuration file, there is an opportunity to validate the content of the configuration file with the following command:
@y
Before you apply changes made to a Compose configuration file, there is an opportunity to validate the content of the configuration file with the following command:
@z

@x
```console
$ docker-compose config
```
@y
```console
$ docker-compose config
```
@z

@x
When this command is run, Docker Compose would read the file `docker-compose.yml`, parse it into a data structure in memory, validate where possible, and print back the _reconstruction_ of that configuration file from its internal representation. If this is not possible due to errors, it would print an error message instead.
@y
When this command is run, Docker Compose would read the file `docker-compose.yml`, parse it into a data structure in memory, validate where possible, and print back the _reconstruction_ of that configuration file from its internal representation. If this is not possible due to errors, it would print an error message instead.
@z

@x
### Build and run the application using Docker Compose
@y
### Build and run the application using Docker Compose
@z

@x
Let’s start our application and confirm that it is running properly.
@y
Let’s start our application and confirm that it is running properly.
@z

@x
```console
$ docker-compose up --build
```
@y
```console
$ docker-compose up --build
```
@z

@x
We pass the `--build` flag so Docker will compile our image and then starts it.
@y
We pass the `--build` flag so Docker will compile our image and then starts it.
@z

@x
> **Note**
>
> Docker Compose is a useful tool, but it has its own quirks. For example, no rebuild is triggered on update to the source code unless the `--build` flag is provided. It is a very common pitfall to edit one's source code, and forget to use the `--build` flag when running `docker-compose up`.
@y
> **Note**
>
> Docker Compose is a useful tool, but it has its own quirks. For example, no rebuild is triggered on update to the source code unless the `--build` flag is provided. It is a very common pitfall to edit one's source code, and forget to use the `--build` flag when running `docker-compose up`.
@z

@x
Since our set-up is now run by Docker Compose, it has assigned it a "project name", so we got a new volume for our CockroachDB instance. This means that our application would fail to connect to the database, because the database does not exist in this new volume. The terminal would display an authentication error for the database:
@y
Since our set-up is now run by Docker Compose, it has assigned it a "project name", so we got a new volume for our CockroachDB instance. This means that our application would fail to connect to the database, because the database does not exist in this new volume. The terminal would display an authentication error for the database:
@z

@x
```
# ... omitted output ...
rest-server             | 2021/05/10 00:54:25 failed to initialise the store: pq: password authentication failed for user totoro
roach                   | *
roach                   | * INFO: Replication was disabled for this cluster.
roach                   | * When/if adding nodes in the future, update zone configurations to increase the replication factor.
roach                   | *
roach                   | CockroachDB node starting at 2021-05-10 00:54:26.398177 +0000 UTC (took 3.0s)
roach                   | build:               CCL v20.1.15 @ 2021/04/26 16:11:58 (go1.13.9)
roach                   | webui:               http://db:8080
roach                   | sql:                 postgresql://root@db:26257?sslmode=disable
roach                   | RPC client flags:    /cockroach/cockroach <client cmd> --host=db:26257 --insecure
roach                   | logs:                /cockroach/cockroach-data/logs
roach                   | temp dir:            /cockroach/cockroach-data/cockroach-temp349434348
roach                   | external I/O path:   /cockroach/cockroach-data/extern
roach                   | store[0]:            path=/cockroach/cockroach-data
roach                   | storage engine:      rocksdb
roach                   | status:              initialized new cluster
roach                   | clusterID:           b7b1cb93-558f-4058-b77e-8a4ddb329a88
roach                   | nodeID:              1
rest-server exited with code 0
rest-server             | 2021/05/10 00:54:25 failed to initialise the store: pq: password authentication failed for user totoro
rest-server             | 2021/05/10 00:54:26 failed to initialise the store: pq: password authentication failed for user totoro
rest-server             | 2021/05/10 00:54:29 failed to initialise the store: pq: password authentication failed for user totoro
rest-server             | 2021/05/10 00:54:25 failed to initialise the store: pq: password authentication failed for user totoro
rest-server             | 2021/05/10 00:54:26 failed to initialise the store: pq: password authentication failed for user totoro
rest-server             | 2021/05/10 00:54:29 failed to initialise the store: pq: password authentication failed for user totoro
rest-server exited with code 1
# ... omitted output ...
```
@y
```
# ... omitted output ...
rest-server             | 2021/05/10 00:54:25 failed to initialise the store: pq: password authentication failed for user totoro
roach                   | *
roach                   | * INFO: Replication was disabled for this cluster.
roach                   | * When/if adding nodes in the future, update zone configurations to increase the replication factor.
roach                   | *
roach                   | CockroachDB node starting at 2021-05-10 00:54:26.398177 +0000 UTC (took 3.0s)
roach                   | build:               CCL v20.1.15 @ 2021/04/26 16:11:58 (go1.13.9)
roach                   | webui:               http://db:8080
roach                   | sql:                 postgresql://root@db:26257?sslmode=disable
roach                   | RPC client flags:    /cockroach/cockroach <client cmd> --host=db:26257 --insecure
roach                   | logs:                /cockroach/cockroach-data/logs
roach                   | temp dir:            /cockroach/cockroach-data/cockroach-temp349434348
roach                   | external I/O path:   /cockroach/cockroach-data/extern
roach                   | store[0]:            path=/cockroach/cockroach-data
roach                   | storage engine:      rocksdb
roach                   | status:              initialized new cluster
roach                   | clusterID:           b7b1cb93-558f-4058-b77e-8a4ddb329a88
roach                   | nodeID:              1
rest-server exited with code 0
rest-server             | 2021/05/10 00:54:25 failed to initialise the store: pq: password authentication failed for user totoro
rest-server             | 2021/05/10 00:54:26 failed to initialise the store: pq: password authentication failed for user totoro
rest-server             | 2021/05/10 00:54:29 failed to initialise the store: pq: password authentication failed for user totoro
rest-server             | 2021/05/10 00:54:25 failed to initialise the store: pq: password authentication failed for user totoro
rest-server             | 2021/05/10 00:54:26 failed to initialise the store: pq: password authentication failed for user totoro
rest-server             | 2021/05/10 00:54:29 failed to initialise the store: pq: password authentication failed for user totoro
rest-server exited with code 1
# ... omitted output ...
```
@z

@x
Because of the way we set up our deployment using `restart_policy`, the failing container is being restarted every 20 seconds. So, in order to fix the problem, we need to log into the database engine and create the user, we've done it before in the []
@y
Because of the way we set up our deployment using `restart_policy`, the failing container is being restarted every 20 seconds. So, in order to fix the problem, we need to log into the database engine and create the user, we've done it before in the []
@z

@x
This is not a big deal. All we have to do is to connect to CockroachDB instance and run the three SQL commands to create the database and the user, as described above in the _Configure the database engine_ section above.
@y
This is not a big deal. All we have to do is to connect to CockroachDB instance and run the three SQL commands to create the database and the user, as described above in the _Configure the database engine_ section above.
@z

@x
So we login into the database engine from another terminal:
@y
So we login into the database engine from another terminal:
@z

@x
```console
$ docker exec -it roach ./cockroach sql --insecure
```
@y
```console
$ docker exec -it roach ./cockroach sql --insecure
```
@z

@x
And execute the same commands as before to create the database `mydb`, the user `totoro`, and to grant that user necessary permissions. Once we do that (and the example application container is automatically restarted), the `rest-service` stops failing and restarting and the console goes quiet.
@y
And execute the same commands as before to create the database `mydb`, the user `totoro`, and to grant that user necessary permissions. Once we do that (and the example application container is automatically restarted), the `rest-service` stops failing and restarting and the console goes quiet.
@z

@x
It would have been possible to connect the volume that we had previously used, but for the purposes of our example it's more trouble than it's worth and it also provided an opportunity to show how to introduce resilience into our deployment via the `restart_policy` Compose file feature.
@y
It would have been possible to connect the volume that we had previously used, but for the purposes of our example it's more trouble than it's worth and it also provided an opportunity to show how to introduce resilience into our deployment via the `restart_policy` Compose file feature.
@z

@x
### Testing the application
@y
### Testing the application
@z

@x
Now let’s test our API endpoint. In the new terminal, run the following command:
@y
Now let’s test our API endpoint. In the new terminal, run the following command:
@z

@x
```console
$ curl http://localhost/
```
@y
```console
$ curl http://localhost/
```
@z

@x
You should receive the following response:
@y
You should receive the following response:
@z

@x
```json
Hello, Docker! (0)
```
@y
```json
Hello, Docker! (0)
```
@z

@x
### Shutting down
@y
### Shutting down
@z

@x
To _stop_ the containers started by Docker Compose, press ctrl+c in the terminal where we run `docker-compose up`. To _remove_ those containers after they had been stopped, run `docker-compose down`.
@y
To _stop_ the containers started by Docker Compose, press ctrl+c in the terminal where we run `docker-compose up`. To _remove_ those containers after they had been stopped, run `docker-compose down`.
@z

@x
### Detached mode
@y
### Detached mode
@z

@x
You can run containers started by the `docker-compose` command in detached mode, just as you would with the `docker` command, by using the `-d` flag. 
@y
You can run containers started by the `docker-compose` command in detached mode, just as you would with the `docker` command, by using the `-d` flag. 
@z

@x
To start the stack, defined by the Compose file in detached mode, run:
@y
To start the stack, defined by the Compose file in detached mode, run:
@z

@x
```console
$ docker-compose up --build -d
```
@y
```console
$ docker-compose up --build -d
```
@z

@x
Then, you can use `docker-compose stop` to stop the containers and `docker-compose down` to remove them.
@y
Then, you can use `docker-compose stop` to stop the containers and `docker-compose down` to remove them.
@z

@x
## Further exploration
@y
## Further exploration
@z

@x
We would suggest running `docker-compose` to see what other commands are available.
@y
We would suggest running `docker-compose` to see what other commands are available.
@z

@x
## Wrap up
@y
## Wrap up
@z

@x
There are some tangential, yet interesting points that were purposefully not covered in this chapter. For the more adventurous reader, this section offers some pointers for further study.
@y
There are some tangential, yet interesting points that were purposefully not covered in this chapter. For the more adventurous reader, this section offers some pointers for further study.
@z

@x
### Persistent storage
@y
### Persistent storage
@z

@x
A _managed volume_ isn't the only way to provide your container with persistent storage. It is highly recommended to get acquainted with available storage options and their use cases, covered in the following part of Docker documentation: [Manage data in Docker](../../storage/index.md).
@y
A _managed volume_ isn't the only way to provide your container with persistent storage. It is highly recommended to get acquainted with available storage options and their use cases, covered in the following part of Docker documentation: [Manage data in Docker](../../storage/index.md).
@z

@x
### CockroachDB clusters
@y
### CockroachDB clusters
@z

@x
We run a single instance of CockroachDB, which was enough for our demonstration. But it is possible to run a CockroachDB _cluster_, which is made of multiple instances of CockroachDB, each instance running in its own container. Since CockroachDB engine is distributed by design, it would have taken us surprisingly little change to our procedure to run a cluster with multiple nodes.
@y
We run a single instance of CockroachDB, which was enough for our demonstration. But it is possible to run a CockroachDB _cluster_, which is made of multiple instances of CockroachDB, each instance running in its own container. Since CockroachDB engine is distributed by design, it would have taken us surprisingly little change to our procedure to run a cluster with multiple nodes.
@z

@x
Such distributed set-up offers interesting possibilities, such as applying _Chaos Engineering_ techniques to simulate parts of the cluster failing and evaluating our application's ability to cope with such failures.
@y
Such distributed set-up offers interesting possibilities, such as applying _Chaos Engineering_ techniques to simulate parts of the cluster failing and evaluating our application's ability to cope with such failures.
@z

@x
If you are interested in experimenting with CockroachDB clusters, check out:
@y
If you are interested in experimenting with CockroachDB clusters, check out:
@z

@x
* [Start a CockroachDB Cluster in Docker](https://www.cockroachlabs.com/docs/v20.2/start-a-local-cluster-in-docker-mac.html) article; and
* Documentation for Docker Compose keywords [`deploy`](../../compose/compose-file/compose-file-v3.md#deploy) and [`replicas`](../../compose/compose-file/compose-file-v3.md#replicas).
@y
* [Start a CockroachDB Cluster in Docker](https://www.cockroachlabs.com/docs/v20.2/start-a-local-cluster-in-docker-mac.html) article; and
* Documentation for Docker Compose keywords [`deploy`](../../compose/compose-file/compose-file-v3.md#deploy) and [`replicas`](../../compose/compose-file/compose-file-v3.md#replicas).
@z

@x
### Other databases
@y
### Other databases
@z

@x
Since we did not run a cluster of CockroachDB instances, you might be wondering whether we could have used a non-distributed database engine. The answer is 'yes', and if we were to pick a more traditional SQL database, such as [PostgreSQL](https://www.postgresql.org/), the process described in this chapter would have been very similar.
@y
Since we did not run a cluster of CockroachDB instances, you might be wondering whether we could have used a non-distributed database engine. The answer is 'yes', and if we were to pick a more traditional SQL database, such as [PostgreSQL](https://www.postgresql.org/), the process described in this chapter would have been very similar.
@z

@x
## Next steps
@y
## Next steps
@z

@x
In this module, we set up a containerised development environment with our application and the database engine running in different containers. We also wrote a Docker Compose file which links the two containers together and provides for easy starting up and tearing down of the development environment.
@y
In this module, we set up a containerised development environment with our application and the database engine running in different containers. We also wrote a Docker Compose file which links the two containers together and provides for easy starting up and tearing down of the development environment.
@z

@x
In the next module, we’ll take a look at one possible approach to running functional tests in Docker. See:
@y
In the next module, we’ll take a look at one possible approach to running functional tests in Docker. See:
@z

@x
[Run your tests](run-tests.md){: .button .outline-btn}
@y
[Run your tests](run-tests.md){: .button .outline-btn}
@z

@x
## Feedback
@y
## Feedback
@z

@x
Help us improve this topic by providing your feedback. Let us know what you think by creating an issue in the [Docker Docs](https://github.com/docker/docker.github.io/issues/new?title=[Golang%20docs%20feedback]){:target="_blank" rel="noopener" class="_"} GitHub repository. Alternatively, [create a PR](https://github.com/docker/docker.github.io/pulls){:target="_blank" rel="noopener" class="_"} to suggest updates.
@y
Help us improve this topic by providing your feedback. Let us know what you think by creating an issue in the [Docker Docs](https://github.com/docker/docker.github.io/issues/new?title=[Golang%20docs%20feedback]){:target="_blank" rel="noopener" class="_"} GitHub repository. Alternatively, [create a PR](https://github.com/docker/docker.github.io/pulls){:target="_blank" rel="noopener" class="_"} to suggest updates.
@z

@x
<br />
@y
<br />
@z
